name: Core Storybook build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'dev'
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_P_KEY }}
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      - name: install deps and predeploy
        run: |
          yarn install
          yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: storybook
          FOLDER: storybook-static
          CLEAN: true
          CLEAN_EXCLUDE: '["CNAME"]'
          TARGET_FOLDER: dev
