import { Meta, Story } from '@storybook/react/types-6-0';
import { TextBoxProps } from '../Types';
declare const _default: Meta<import("@storybook/react/types-6-0").Args>;
export default _default;
export declare const Filled: Story<TextBoxProps>;
export declare const Outlined: Story<TextBoxProps>;
export declare const Bare: Story<TextBoxProps>;
export declare const ColouredOutline: Story<TextBoxProps>;
export declare const ChangedFont: Story<TextBoxProps>;
export declare const BareCentered: Story<TextBoxProps>;
export declare const NumbersOnly: Story<TextBoxProps>;
export declare const PrefixComponent: Story<TextBoxProps>;
export declare const FilledSuffix: Story<TextBoxProps>;
export declare const SuffixComponent: Story<TextBoxProps>;
export declare const SizeSet: Story<TextBoxProps>;
